In [3]:
import pandas as pd
import numpy as np
from sklearn import metrics

In [6]:
df=pd.read_csv("C:\\Users\\LENOVO\\Downloads\\play_tennis.csv")
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [7]:
from sklearn import preprocessing
string_int=preprocessing.LabelEncoder()
df=df.apply(string_int.fit_transform)
df

    outlook  temp  humidity  wind  play
0         2     1         0     1     0
1         2     1         0     0     0
2         0     1         0     1     1
3         1     2         0     1     1
4         1     0         1     1     1
5         1     0         1     0     0
6         0     0         1     0     1
7         2     2         0     1     0
8         2     0         1     1     1
9         1     2         1     1     1
10        2     2         1     0     1
11        0     2         0     0     1
12        0     1         1     1     1
13        1     2         0     0     0

In [8]:
x=df[['outlook','temp','humidity','wind']]
y=df['play']

In [9]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.1,random_state=1)

In [10]:
from sklearn.naive_bayes import GaussianNB
k=GaussianNB()
k.fit(xtrain,ytrain)
p=k.predict(xtest)

In [11]:
#initial accuracy
from sklearn.metrics import accuracy_score
print("accuracy is:",accuracy_score(p,ytest))

accuracy is: 1.0

In [12]:
fp=k.predict([[1,1,0,1]])
print("the final label is:",fp)

the final label is: [1]

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(